/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author alexp
 */
public class BuscarReservacion extends javax.swing.JFrame {
    public static MenuPrincipal m1;
    /**
     * Creates new form BuscarReservacion
     */
    public BuscarReservacion(MenuPrincipal m1) {
        initComponents();
        this.m1=m1;
        m1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscarbutton = new javax.swing.JToggleButton();
        BuscarTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MostrarReservacionTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        Buscarbutton.setText("Buscar");
        Buscarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Buscarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        BuscarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTextoActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 170, -1));

        MostrarReservacionTextArea.setColumns(20);
        MostrarReservacionTextArea.setRows(5);
        jScrollPane1.setViewportView(MostrarReservacionTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda de reservacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbuttonActionPerformed
       String dato;
       dato=BuscarTexto.getText();
       BuscarTexto.setText("");
       
       
       
       MostrarReservacionTextArea.setText(dato);
    }//GEN-LAST:event_BuscarbuttonActionPerformed

    private void BuscarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarReservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarReservacion( m1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuscarTexto;
    private javax.swing.JToggleButton Buscarbutton;
    private javax.swing.JTextArea MostrarReservacionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
