/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import hashtablesPrim.*;
import proyecto.hotel.*;

/**
 *
 * @author alexp
 */
public class MenuPrincipal extends javax.swing.JFrame {
    public static MenuPrincipal MenuPrincipal;
    static public ArbolHabitacion arbolHabitacion;
    static public ArbolReservacion arbolReservacion;
    static public registroHash hashTable;
    
    public MenuPrincipal() {
        initComponents();
        LectorArchivos lector = new LectorArchivos();
        if(arbolHabitacion == null || arbolReservacion == null || hashTable == null);
            arbolHabitacion = lector.abridorArchivoHistorico();
            arbolReservacion = lector.abridorArchivoReservas();
            hashTable = lector.abridorArchivoEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BusquedaClientes = new javax.swing.JButton();
        HistorialReservacion = new javax.swing.JButton();
        BusquedaReservacion = new javax.swing.JToggleButton();
        CheckIn = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Imagenmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BusquedaClientes.setBackground(new java.awt.Color(255, 255, 255));
        BusquedaClientes.setForeground(new java.awt.Color(0, 0, 0));
        BusquedaClientes.setText("Búsqueda de clientes");
        BusquedaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaClientesActionPerformed(evt);
            }
        });
        getContentPane().add(BusquedaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 140, 160, 30));

        HistorialReservacion.setBackground(new java.awt.Color(255, 255, 255));
        HistorialReservacion.setForeground(new java.awt.Color(0, 0, 0));
        HistorialReservacion.setText("Historial de Reservación");
        HistorialReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(HistorialReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, 30));

        BusquedaReservacion.setBackground(new java.awt.Color(255, 255, 255));
        BusquedaReservacion.setForeground(new java.awt.Color(0, 0, 0));
        BusquedaReservacion.setText("Búsqueda de reservación");
        BusquedaReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaReservacionActionPerformed(evt);
            }
        });
        getContentPane().add(BusquedaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 180, -1, 30));

        CheckIn.setBackground(new java.awt.Color(255, 255, 255));
        CheckIn.setForeground(new java.awt.Color(0, 0, 0));
        CheckIn.setText("Check In");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, -1));

        Checkout.setBackground(new java.awt.Color(255, 255, 255));
        Checkout.setForeground(new java.awt.Color(0, 0, 0));
        Checkout.setText("Check out");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(Checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 160, -1));

        Salir.setBackground(new java.awt.Color(255, 255, 255));
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagenmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imenu.jpg"))); // NOI18N
        jPanel1.add(Imagenmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 560, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void BusquedaReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaReservacionActionPerformed
        BuscarReservacion ventana3 = new BuscarReservacion(MenuPrincipal);
        ventana3.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_BusquedaReservacionActionPerformed

    private void BusquedaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaClientesActionPerformed
        BuscarClientes ventana1 = new BuscarClientes(MenuPrincipal);
        ventana1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_BusquedaClientesActionPerformed

    private void HistorialReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialReservacionActionPerformed
        BuscarHistorial ventana2 = new BuscarHistorial(MenuPrincipal);
        ventana2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_HistorialReservacionActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        CheckIn ventana4 = new CheckIn(MenuPrincipal);
        ventana4.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_CheckInActionPerformed

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed
        CheckOut ventana5 = new CheckOut(MenuPrincipal);
        ventana5.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_CheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusquedaClientes;
    private javax.swing.JToggleButton BusquedaReservacion;
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton Checkout;
    private javax.swing.JButton HistorialReservacion;
    private javax.swing.JLabel Imagenmenu;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
