/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIproyecto.ventanasInterfaz;

import hashtablesPrim.*;
import proyecto.hotel.*;

/**
 *
 * @author joseg
 */
public class Menu1Home extends javax.swing.JFrame {
    public static Menu1Home vMenu1;
    static public ArbolHabitacion arbolHabitacion;
    static public ArbolReservacion arbolReservacion;
    static public registroHash hashTable;
    static public ArrayList habitaciones;
    /**
     * Creates new form Menu1
     */
    public Menu1Home() {
        initComponents();
        this.vMenu1=vMenu1;
        this.setVisible(true);
        LectorArchivos lector = new LectorArchivos();
        if(arbolHabitacion == null || arbolReservacion == null || hashTable == null || habitaciones == null);
            arbolHabitacion = lector.abridorArchivoHistorico();
            arbolReservacion = lector.abridorArchivoReservas();
            hashTable = lector.abridorArchivoEstado();
            habitaciones = lector.abridorArchivoHabitaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarclientesBoton = new javax.swing.JButton();
        buscarreservBoton = new javax.swing.JButton();
        checkinBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        checkoutBoton = new javax.swing.JButton();
        historialhabboton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/fondoHotel.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarclientesBoton.setBackground(new java.awt.Color(0, 153, 204));
        buscarclientesBoton.setText("Buscar clientes");
        buscarclientesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclientesBotonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarclientesBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        buscarreservBoton.setBackground(new java.awt.Color(0, 153, 204));
        buscarreservBoton.setText("Buscar reservas");
        buscarreservBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarreservBotonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarreservBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        checkinBoton.setBackground(new java.awt.Color(0, 153, 204));
        checkinBoton.setText("Check-in");
        checkinBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinBotonActionPerformed(evt);
            }
        });
        getContentPane().add(checkinBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Hotel Booking");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        checkoutBoton.setBackground(new java.awt.Color(0, 153, 204));
        checkoutBoton.setText("Check-out");
        checkoutBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBotonActionPerformed(evt);
            }
        });
        getContentPane().add(checkoutBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, -1));

        historialhabboton1.setBackground(new java.awt.Color(0, 153, 204));
        historialhabboton1.setText("Historial de habitaciones");
        historialhabboton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialhabboton1ActionPerformed(evt);
            }
        });
        getContentPane().add(historialhabboton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/esp3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -130, 530, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkinBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinBotonActionPerformed
ventanaCheckin vCheckin=new ventanaCheckin(this);
vCheckin.setVisible(true);
vCheckin.toFront();
    }//GEN-LAST:event_checkinBotonActionPerformed

    private void buscarclientesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclientesBotonActionPerformed
ventanaBuscarclientes vClientes=new ventanaBuscarclientes(this);
vClientes.setVisible(true);
vClientes.toFront();
    }//GEN-LAST:event_buscarclientesBotonActionPerformed

    private void buscarreservBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarreservBotonActionPerformed
ventanaBuscarreservas vReservas=new ventanaBuscarreservas(this);
vReservas.setVisible(true);
vReservas.toFront();
    }//GEN-LAST:event_buscarreservBotonActionPerformed

    private void checkoutBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBotonActionPerformed
ventanaCheckOut vCheckout=new ventanaCheckOut(this);
vCheckout.setVisible(true);
vCheckout.toFront();
    }//GEN-LAST:event_checkoutBotonActionPerformed

    private void historialhabboton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialhabboton1ActionPerformed
ventanaHistorial vHistorial=new ventanaHistorial(this);
vHistorial.setVisible(true);
vHistorial.toFront();
    }//GEN-LAST:event_historialhabboton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarclientesBoton;
    private javax.swing.JButton buscarreservBoton;
    private javax.swing.JButton checkinBoton;
    private javax.swing.JButton checkoutBoton;
    private javax.swing.JButton historialhabboton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    

}
