/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIproyecto.ventanasInterfaz;

/**
 *
 * @author joseg
 */
public class ventanaCheckin extends javax.swing.JFrame {

    public static Menu1Home vCheckin;
    /**
     * Creates new form ventanaCheckin
     */
    public ventanaCheckin(Menu1Home vCheckin1) {
        this.vCheckin=vCheckin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVolver = new javax.swing.JButton();
        tiraAzul = new javax.swing.JLabel();
        insertarCI = new javax.swing.JTextField();
        resultadosMensaje = new javax.swing.JScrollPane();
        mensajeCheckinLabel = new javax.swing.JLabel();
        botonBuscarCI = new javax.swing.JButton();
        CILabel = new javax.swing.JLabel();
        CheckInIcono = new javax.swing.JLabel();
        fondodeBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVolver.setBackground(new java.awt.Color(0, 153, 204));
        botonVolver.setText("Volver a menú");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        tiraAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/tiraAzul.png"))); // NOI18N
        tiraAzul.setText("jLabel1");
        tiraAzul.setPreferredSize(new java.awt.Dimension(210, 300));
        getContentPane().add(tiraAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, -1));
        getContentPane().add(insertarCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));
        getContentPane().add(resultadosMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, 70));

        mensajeCheckinLabel.setForeground(new java.awt.Color(0, 0, 0));
        mensajeCheckinLabel.setText("Mensaje");
        getContentPane().add(mensajeCheckinLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        botonBuscarCI.setBackground(new java.awt.Color(0, 153, 204));
        botonBuscarCI.setText("Buscar");
        botonBuscarCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarCIActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));

        CILabel.setForeground(new java.awt.Color(0, 0, 0));
        CILabel.setText("Cédula del huesped");
        getContentPane().add(CILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        CheckInIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/checkin.png"))); // NOI18N
        CheckInIcono.setText("jLabel1");
        getContentPane().add(CheckInIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, -1));

        fondodeBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/blanco.png"))); // NOI18N
        fondodeBlanco.setText("jLabel1");
        fondodeBlanco.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(fondodeBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBuscarCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarCIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonBuscarCIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaCheckin(vCheckin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CILabel;
    private javax.swing.JLabel CheckInIcono;
    private javax.swing.JButton botonBuscarCI;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel fondodeBlanco;
    private javax.swing.JTextField insertarCI;
    private javax.swing.JLabel mensajeCheckinLabel;
    private javax.swing.JScrollPane resultadosMensaje;
    private javax.swing.JLabel tiraAzul;
    // End of variables declaration//GEN-END:variables
}
