/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIproyecto.ventanasInterfaz;

import hashtablesPrim.*;

/**
 *
 * @author joseg
 */
public class ventanaBuscarclientes extends javax.swing.JFrame {

    public static Menu1Home vClientes;
    public registroHash hashTable = Menu1Home.hashTable;
    /**
     * Creates new form ventanaBuscarclientes
     */
    public ventanaBuscarclientes(Menu1Home vClientes) {
        initComponents();
        this.vClientes=vClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonVolver = new javax.swing.JButton();
        tiraAzul = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        historialNumhabNomApe = new javax.swing.JLabel();
        botonBuscarnombreapellido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        Nombre = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        fondoClientes = new javax.swing.JLabel();
        fondodeBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVolver.setBackground(new java.awt.Color(0, 153, 204));
        botonVolver.setText("Volver a menú");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, -1));

        tiraAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/tiraAzul.png"))); // NOI18N
        tiraAzul.setText("jLabel1");
        tiraAzul.setPreferredSize(new java.awt.Dimension(210, 300));
        getContentPane().add(tiraAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 40, -1));
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        apellidoLabel.setForeground(new java.awt.Color(0, 0, 0));
        apellidoLabel.setText("Apellido:");
        getContentPane().add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        historialNumhabNomApe.setForeground(new java.awt.Color(0, 0, 0));
        historialNumhabNomApe.setText("Número de habitación:");
        getContentPane().add(historialNumhabNomApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        botonBuscarnombreapellido.setBackground(new java.awt.Color(0, 153, 204));
        botonBuscarnombreapellido.setText("Buscar");
        botonBuscarnombreapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarnombreapellidoActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarnombreapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 70, -1));

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane2.setViewportView(Salida);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 100));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        nombreLabel1.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel1.setText("Nombre:");
        getContentPane().add(nombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        fondoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/huespedes_1.png"))); // NOI18N
        fondoClientes.setText("jLabel1");
        getContentPane().add(fondoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, -1));

        fondodeBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIproyecto/imagenesGUI/blanco.png"))); // NOI18N
        fondodeBlanco.setText("jLabel1");
        fondodeBlanco.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(fondodeBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBuscarnombreapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarnombreapellidoActionPerformed
        if(!Nombre.getText().isBlank() && !Apellido.getText().isBlank()){
            clientes cliente = hashTable.buscarHash(Nombre.getText(), Apellido.getText());
            if(cliente == null){
                Salida.setText("El Cliente no Existe");
            }else{
                Salida.setText(cliente.toString());
            }
            
        }
    }//GEN-LAST:event_botonBuscarnombreapellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaBuscarclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaBuscarclientes(vClientes).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextArea Salida;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JButton botonBuscarnombreapellido;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel fondoClientes;
    private javax.swing.JLabel fondodeBlanco;
    private javax.swing.JLabel historialNumhabNomApe;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel tiraAzul;
    // End of variables declaration//GEN-END:variables
}
